Split shop building in independent single job for optimization
PrestaShop/ga.tests.ui.pr pull request #44
Opened 2023-08-17 10:25 UTC by jolelievre

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Split docker building in an independent single job for optimization, then the sources and dump are shared as artifacts for the following steps that handles test commands thus making the setup of the shop faster<br><br>This PR comes with a related one in the core https://github.com/PrestaShop/PrestaShop/pull/33690 Not required but it allows optimizing a bit more the test phase (no need to install composer and node in the docker during the second test phase since everything has already been installed and built)<br/><br/>The workflow itself has multiple optimizations:<br><ul><li>Only one build for all following campaigns</li><li>Sanity tests are handled separately because they already handle installation, that saves some build time and improves stability</li><li>Keycloak service is only built for API tests</li><li>Long campaigns are started in priority to optimize the total duration</li><li>You can now run a single dedicated campaign</li><li>Javascript dependencies are run in parallel to win a bit of time, a systematic check is performed at the end to make sure the built is over</li><li>Docker images are pulled and built early in background while dependencies are built/installed to save some time during the final build</li></ul><br><br>New features:<ul><li>Possibility to run a single campaign</li><li>Possibility run force fast fail (still false by default)</li></ul>
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Sponsor company   | ~
| How to test?      | ~

### Remaining possible improvement
- the base branch from PR could be used to avoid selecting it manually

# Benchmark

## Using the optimized PR https://github.com/PrestaShop/PrestaShop/pull/33690
Only this benchmark was run without another build in parallel for the sake of showing the improvement

### With the split workflow

#### Without cache
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6207662484
Total duration: [31m 5s](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6207662484/usage)
Total run time: 7h 20m 47s

#### With cache already set
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208145339
Total duration: [31m 18s](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208145339/usage)
Total run time: 7h 1m 43s

> [!NOTE]  
> In both cases sanity tests are fixed

### With the split framework but less cache management

#### Without cache
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6278375332

#### With cache already set
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6276944907
Total duration: [33m 30s](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6276944907/usage)
Total run time: 7h 18m 49s

### Without the split workflow

#### No cache system
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208570595
Total duration: [54m 49s](https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208570595/usage)
Total run time: 10h 30m 48s

> [!WARNING]  
> Sanity tests failing, which makes the total duration longer because failing tests are long to finish

# Other PRs

## Merge PR
https://github.com/PrestaShop/PrestaShop/pull/33952
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208800734

## PR to update doctrine that failed sanity tests
https://github.com/PrestaShop/PrestaShop/pull/33459
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6226478282

## PR targeting 8.1.x

https://github.com/PrestaShop/PrestaShop/pull/33930

### Split jobs
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6226487438

### No split jobs
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6222099607

## PR that updates ps_linklist
https://github.com/PrestaShop/PrestaShop/pull/33853

### Split jobs
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6208823720

### No split jobs
https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/6222085952

2023-08-17 10:32 UTC, boubkerbribri commented
I love this, did you start a test somewhere ?

2023-08-17 13:47 UTC, jolelievre commented
@boubkerbribri yep one of the tests https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5891548178 but it's not working yet I'm still experiencing

2023-08-21 08:55 UTC, mflasquin approved these changes

2023-08-21 09:46 UTC, M0rgan01 commented on .github/workflows/pr_test.yml
> +          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml up -d --build
by default it takes the docker-compose.yml file
```suggestion
          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose up -d --build
```

2023-08-21 09:46 UTC, M0rgan01 commented on .github/workflows/pr_test.yml
> +          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml up -d --build
```suggestion
          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose up -d --build
```

2023-08-21 09:46 UTC, M0rgan01 commented on .github/workflows/pr_test.yml
> +          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose -f docker-compose.yml up -d --build mysql
```suggestion
          USER_ID=$(id -u) GROUP_ID=$(id -g) docker-compose up -d --build mysql
```

2023-08-21 09:46 UTC, M0rgan01 commented on .docker/docker-compose.yml
> +        image: prestashop-mysql-image
why not use the official mysql image? Same for keycloak

2023-08-21 09:46 UTC, M0rgan01 commented on .docker/docker-compose.yml
> +        image: prestashop-git-image
Is a dockerfile missing? or use the core one but I don't see a build

2023-08-22 12:10 UTC, jolelievre commented
Comparison:
Regular single job: https://github.com/jolelievre/ga.tests.ui.pr/actions/runs/5938546267 started at 14h09

2023-09-19 08:50 UTC, Progi1984 approved these changes

2023-09-20 09:46 UTC, matks requested changes
@jolelievre This PR needs a rebase 😢

2023-09-25 09:35 UTC, boubkerbribri approved these changes

2023-09-25 12:23 UTC, Progi1984 approved these changes

2023-09-25 13:16 UTC, merged

2023-09-25 13:29 UTC, matks commented
Great job @jolelievre and thank you @Progi1984 and @boubkerbribri for the extensive review work